FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY config/ ./config/
COPY data/raw/ ./data/raw/

ENV MLFLOW_TRACKING_URI=http://mlflow.mlflow.svc.cluster.local:5000

CMD [ "sh", "-c", "python src/preprocess.py && python src/train.py"]