apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic?ref=2.17.0
images:
  - name: gcr.io/ml-pipeline/minio
    newName: minio/minio
    newTag: RELEASE.2019-08-14T20-37-41Z