apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Bilal-SSDL/loan-default-mlops-platform.git
    targetRevision: HEAD
    path: kubernetes/platform/kubeflow/cluster-scoped
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true