apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loan-kserve
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/Bilal-SSDL/loan-default-mlops-platform.git
    targetRevision: HEAD
    path: kubernetes/workloads/kserve
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
