apiVersion: v1
kind: Service
metadata:
  name: loan-api
  namespace: application
  labels:
    app: loan-api
spec:
  type: ClusterIP
  selector:
    app: loan-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
